import { FC, ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { SessionProvider } from "next-auth/react";

import "@/styles/globals.css";

const inter = Inter({
  display: "swap",
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/sonner";

import QueryProvider from "@/components/providers/query-provider";

import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<IRootLayoutProps> = async ({ children }) => {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn("font-inter antialiased", inter.variable)}>
          <QueryProvider>{children}</QueryProvider>
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
};

export default RootLayout;
